# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=300)),
                ('date_of_comment', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pictures', models.BinaryField(max_length=4621440)),
                ('likes', models.IntegerField(default=0)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('name_of_picture', models.CharField(max_length=50)),
                ('id_pictures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Picture')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginer.User')),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='id_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Picture'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginer.User'),
        ),
    ]
