# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginer', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Picture'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginer.User'),
        ),
    ]
