# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_picture_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
