# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160910_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='check',
            field=models.IntegerField(default=0),
        ),
    ]
