# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_picture_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_size',
            field=models.CharField(default='', max_length=20),
        ),
    ]
