# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('data_of_reg', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
                ('nikname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
