# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginer', '0002_auto_20160930_2219'),
        ('loginer', '0002_auto_20160922_2203'),
    ]

    operations = [
    ]
